### ISSUE TITLE
【feat】iOS Component

### ISSUE THREAD

**Issue by ZhouYixun** [ZhouYixun/sonic-agent#32]
1、Listen iOS Devices
2、UI testing for iOS Devices
3、Others like Android Component（Like remote）

1、监听iOS设备
2、iOS设备自动化
3、其他类似安卓的模块（远控等等）

**Comment by zhangpeibisha** [comment]
你好，可以咨询下你们iOS录屏的方案吗,我目前知道一个方案是：https://github.com/danielpaulus/quicktime_video_hack/blob/main/doc/technical_documentation.md，但是这个方案对wda是有影响的，每次启动视频的时候都会重启USB接口导致USB启动的服务挂掉。。。

**Comment by ZhouYixun** [comment]
> 你好，可以咨询下你们iOS录屏的方案吗,我目前知道一个方案是：[https://github.com/danielpaulus/quicktime_video_hack/blob/main/doc/technical_documentation.md，但是这个方案对wda是有影响的，每次启动视频的时候都会重启USB接口导致USB启动的服务挂掉。。。](https://github.com/danielpaulus/quicktime_video_hack/blob/main/doc/technical_documentation.md%EF%BC%8C%E4%BD%86%E6%98%AF%E8%BF%99%E4%B8%AA%E6%96%B9%E6%A1%88%E5%AF%B9wda%E6%98%AF%E6%9C%89%E5%BD%B1%E5%93%8D%E7%9A%84%EF%BC%8C%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E8%A7%86%E9%A2%91%E7%9A%84%E6%97%B6%E5%80%99%E9%83%BD%E4%BC%9A%E9%87%8D%E5%90%AFUSB%E6%8E%A5%E5%8F%A3%E5%AF%BC%E8%87%B4USB%E5%90%AF%E5%8A%A8%E7%9A%84%E6%9C%8D%E5%8A%A1%E6%8C%82%E6%8E%89%E3%80%82%E3%80%82%E3%80%82)

直接将投屏的帧记录下来，ffmpeg转换成mp4就行

**Comment by zhangpeibisha** [comment]
> > 你好，可以咨询下你们iOS录屏的方案吗,我目前知道一个方案是：[https://github.com/danielpaulus/quicktime_video_hack/blob/main/doc/technical_documentation.md，但是这个方案对wda是有影响的，每次启动视频的时候都会重启USB接口导致USB启动的服务挂掉。。。](https://github.com/danielpaulus/quicktime_video_hack/blob/main/doc/technical_documentation.md%EF%BC%8C%E4%BD%86%E6%98%AF%E8%BF%99%E4%B8%AA%E6%96%B9%E6%A1%88%E5%AF%B9wda%E6%98%AF%E6%9C%89%E5%BD%B1%E5%93%8D%E7%9A%84%EF%BC%8C%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E8%A7%86%E9%A2%91%E7%9A%84%E6%97%B6%E5%80%99%E9%83%BD%E4%BC%9A%E9%87%8D%E5%90%AFUSB%E6%8E%A5%E5%8F%A3%E5%AF%BC%E8%87%B4USB%E5%90%AF%E5%8A%A8%E7%9A%84%E6%9C%8D%E5%8A%A1%E6%8C%82%E6%8E%89%E3%80%82%E3%80%82%E3%80%82)
> 
> 直接将投屏的帧记录下来，ffmpeg转换成mp4就行

这个投屏的帧你们是如何获取的哦。自己使用XCUITest的API进行高速截图完成的吗？还是使用quciktime的能力拿到的哦。方便给个获取录屏的数据的demo吗谢谢啦，我目前也在编写agent-ios的代码，想学习下你们的技术。谢谢～
