### ISSUE TITLE
【feat】【测试用例管理】【测试用例】【步骤信息】在这里写了很多用例之后，感觉会比较难找，到时候 能做个下拉搜索吗

### ISSUE THREAD

**Issue by Kant-LJF** [ZhouYixun/sonic-agent#48]
<img width="660" alt="5ed8060837d5ff6216392614f8b1ae0" src="https://user-images.githubusercontent.com/50821154/139652637-41ab29e2-66f8-41e0-9956-67a13952137a.png">

**Comment by ZhouYixun** [comment]
Good issue!
