### ISSUE TITLE
【Bug】控件BUG

### ISSUE THREAD

**Issue by cooler1779** [ZhouYixun/sonic-agent#53]
使用Appium xpath控件时 appium能运行 sonic的控件不能运行（具体看视频演示）

https://user-images.githubusercontent.com/41600632/141071521-c6a59718-9f47-46c4-9193-123a4d204fa2.mp4

https://user-images.githubusercontent.com/41600632/141071547-295bdd3a-9f0a-47d1-bd06-7836863fe022.mp4

**Comment by ZhouYixun** [comment]
已Fixed，如果还出现该情况，请将这issue reopen！
